# Define build arguments
# GO_VERSION is updated automatically to match go.mod, see Makefile
ARG PKG_NAME=github.com/rudderlabs/keydb

# Build stage
FROM golang:1.26.6-alpine3.23@sha256:e57c41c1d5864341031181b0db34b9a537bb5773eb6428e4e5bdaea0f9135406 AS builder

# Install necessary dependencies
RUN apk --no-cache add --update make tzdata ca-certificates gcc musl-dev

# Create app directory
RUN mkdir /app
WORKDIR /app

# Copy Go modules files and download dependencies
COPY go.mod .
COPY go.sum .
RUN go mod download

ARG VERSION
ARG COMMIT_HASH
ARG BUILD_DATE
ARG REVISION

# Copy application source code and build binary
COPY . .
RUN go build \
    -ldflags="-s -w \
    -X 'github.com/rudderlabs/keydb/release.version=${VERSION}' \
    -X 'github.com/rudderlabs/keydb/release.commit=${COMMIT_HASH}' \
    -X 'github.com/rudderlabs/keydb/release.buildDate=${BUILD_DATE}' \
    -X 'github.com/rudderlabs/keydb/release.builtBy=${REVISION}'" \
    -o ./keydb-scaler ./cmd/scaler

# Final stage
FROM alpine:3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

# Update and install additional packages
RUN apk --no-cache upgrade && \
    apk --no-cache add tzdata curl bash

# Copy built binary from previous stage
COPY --from=builder /app/keydb-scaler ./

# Expose the HTTP server port
EXPOSE 8080

# Specify default command to run when container starts
CMD ["/keydb-scaler"]
