# Default values for keydb-scaler.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: rudderstack/rudder-keydb-scaler
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector:
  karpenter.sh/nodepool: critical
tolerations:
  - effect: NoSchedule
    key: type
    value: critical

affinity: {}

# KeyDB node addresses that the scaler will connect to
nodeAddresses: [
  "keydb-0.keydb-headless.loveholidays.svc.cluster.local:50051",
  "keydb-1.keydb-headless.loveholidays.svc.cluster.local:50051",
  "keydb-2.keydb-headless.loveholidays.svc.cluster.local:50051"
]

# Configuration for the scaler
config:
  # Total hash ranges for the client
  totalHashRanges: 128
  # Number of retries for client operations
  retryCount: 3
  # Delay between retries
  retryDelay: 1s
