apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-keydb-operator
  labels:
    app: {{ .Release.Name }}-keydb-operator
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-keydb-operator
    release: {{ .Release.Name }}
