# Default values for keydb-operator.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: rudderstack/rudder-keydb-operator
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# KeyDB node addresses that the operator will connect to
nodeAddresses: [
  "keydb-0.keydb-headless.loveholidays.svc.cluster.local:50051",
  "keydb-1.keydb-headless.loveholidays.svc.cluster.local:50051",
  "keydb-2.keydb-headless.loveholidays.svc.cluster.local:50051"
]

# Configuration for the operator
config:
  # Total hash ranges for the client
  totalHashRanges: 128
  # Number of retries for client operations
  retryCount: 3
  # Delay between retries
  retryDelay: 1s
